spring:
  profiles:
    active: dev

org:
  gradle:
    daemon: false

jwt:
  header: Authorization
  secret: Tm92YUhvbWVQYWdlc2FkZmFzZGZhc2RmYXNkZnNhZGY=
  access-token-validity-in-seconds: 6000 # 10 min